import { type NextPage } from "next";
import Head from "next/head";
import { Card } from "~/Components/Card";
import Sidebar from "~/Components/Sidemenu";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: sensors, isLoading, error } = api.sensorData.getData.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  return (
    <>
      <Head>
        <title>AgriData</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen">
        <Sidebar />
        <main className="w-full bg-gradient-to-b from-[#2e026d] to-[#15162c] p-12">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {Object.keys(sensors.data).map((column) => (
              <Card
                key={column}
                href={`/graph?dataName=${column}`}
                DataName={column}
                DataPoint={sensors.data[column as keyof typeof column]}
              />
            ))}
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
