import { type NextPage } from "next";
import Head from "next/head";
import { Card } from "~/Components/Card";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: sensors, isLoading, error } = api.sensorData.getData.useQuery();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-screen p-12 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {Object.keys(sensors.data).map((column) => (
            <Card key={column} href={`/${column}`} DataName={column} DataPoint={sensors.data[column as keyof typeof column]} />
          ))}
        </div>

      </main >
    </>
  );
};

export default Home;
